name: nightly

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: Cook Variables from gradle.properties
        run : |
          name=$(grep '^extName=' gradle.properties | cut -d'=' -f2)
          echo "NAME=$name Extension" >> $GITHUB_ENV
          id=$(grep '^extId=' gradle.properties | cut -d'=' -f2)
          echo "TAG=$id" >> $GITHUB_ENV

      - name: Make Environment
        run: |
          version=$( echo ${{ github.event.head_commit.id }} | cut -c1-7 )
          echo "VERSION=v$version" >> $GITHUB_ENV
          echo -e '## ${{ env.NAME }}\n${{ github.event.head_commit.message }}' > commit.txt
          echo "APP_PATH=app/build/${{ env.TAG }}-$version.eapk" >> $GITHUB_ENV
          chmod +x ./gradlew
      
      - name: Build Debug APK
        run: |
          ./gradlew assembleDebug
      
      - name: Sign Debug APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/debug
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildType: debug
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      
      - name: Rename Signed APK
        run: |
          mv app/build/outputs/apk/debug/app-debug-signed.apk ${{ env.APP_PATH }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.APP_PATH }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          tag_name: ${{ env.VERSION }}
          body_path: commit.txt
          name: ${{ env.VERSION }}
          files: ${{ env.APP_PATH }}

      - name: Delete Old Releases
        uses: sgpublic/delete-release-action@master
        with:
          release-drop: true
          release-keep-count: 2
          release-drop-tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
